create table food(
    adm0_id INT ,
    adm0_name VARCHAR(100),
    adm1_id INT,
    adm1_name VARCHAR(100),
    mkt_id INT,
    mkt_name VARCHAR(100),
    cm_id INT,
    cm_name VARCHAR(100),
    cur_id INT,
    cur_name VARCHAR(100),
    pt_id INT,
    pt_name VARCHAR(100),
    noofunits INT,
    um_name VARCHAR(100),
    mp_month INT,
    mp_year INT,
    mp_price INT,
    mp_commoditysource VARCHAR(100)
)